import { z } from 'zod';

export const PestScoutingSchema = z.object({
  id: z.string().uuid(),
  orgId: z.string().uuid(),
  plotId: z.string().uuid(),
  observedOn: z.string(),
  observerId: z.string().uuid().nullable().optional(),
  target: z.string(),
  category: z.enum(['pest', 'disease', 'weed', 'beneficial', 'abiotic']),
  severity: z.enum(['none', 'low', 'moderate', 'high', 'severe']),
  incidencePct: z.union([z.string(), z.number()]).nullable().optional(),
  sampleSize: z.number().int().nullable().optional(),
  stageBbch: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
  photos: z.array(z.string()),
  metadata: z.record(z.unknown()),
  createdAt: z.string(),
});
export type PestScouting = z.infer<typeof PestScoutingSchema>;

export const SprayRecordSchema = z.object({
  id: z.string().uuid(),
  orgId: z.string().uuid(),
  plotId: z.string().uuid(),
  scoutingId: z.string().uuid().nullable().optional(),
  appliedAt: z.string(),
  endedAt: z.string().nullable().optional(),
  operator: z.string(),
  target: z.string().nullable().optional(),
  productName: z.string(),
  activeIngredient: z.string(),
  registrationNo: z.string().nullable().optional(),
  doseAmount: z.union([z.string(), z.number()]),
  doseUnit: z.string(),
  waterLPerHa: z.union([z.string(), z.number()]).nullable().optional(),
  areaHa: z.union([z.string(), z.number()]),
  phiDays: z.number().int(),
  reiHours: z.number().int().nullable().optional(),
  equipment: z.string().nullable().optional(),
  windKmh: z.union([z.string(), z.number()]).nullable().optional(),
  tempC: z.union([z.string(), z.number()]).nullable().optional(),
  rhPct: z.union([z.string(), z.number()]).nullable().optional(),
  notes: z.string().nullable().optional(),
  metadata: z.record(z.unknown()),
  voidedAt: z.string().nullable().optional(),
  voidedBy: z.string().uuid().nullable().optional(),
  voidReason: z.string().nullable().optional(),
  recordedBy: z.string().uuid().nullable().optional(),
  createdAt: z.string(),
});
export type SprayRecord = z.infer<typeof SprayRecordSchema>;
